name: Workflow_test_Docker_v2
on:
  push:
    branches:
      - devel

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: Test workflow using docker

    env:
        docker_opt: >-
            --rm 
            -v ${{ github.workspace }}:/workspace 
            -w /workspace 

    steps:
    - name: Initialisation of the test workflow
      uses: AdityaGarg8/remove-unwanted-software@v1
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'

    - name: Checkout the GitHub repository to the workspace
      uses: actions/checkout@v4

    - name: Running the docker container
      uses: rhaschke/docker-run-action@v5
      with:
        image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_10_6_30-slc7_amd64_gcc700:latest
        options: ${{ env.docker_opt }}
        shell: bash
        run: |
          mkdir nanoAODCustomisation && cd nanoAODCustomisation
          cp -r /workspace/* ./
          scram b -j 8
          cd test_Customisers/test/
          echo "#####################"
          echo "Beginning cmsRun job"
          echo "#####################"
          cmsRun test_v1_2016ULpostVFP_MC_config.py
          echo "#####################"
          echo "Ending cmsRun job"
          echo "#####################"
