name: Workflow_test_Docker_v2
on:
  push:
    branches:
      - devel

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    name: Test workflow using docker

    env:
        docker_opt: >-
            --rm 
            -v ${{ github.workspace }}:/nanoAODCustomisation
            -w /nanoAODCustomisation

    steps:
    - name: Initialisation of the test workflow
      uses: AdityaGarg8/remove-unwanted-software@v1
      with:
        remove-android: 'true'
        remove-dotnet: 'true'
        remove-haskell: 'true'

    - name: Checkout the GitHub repository to the workspace
      uses: actions/checkout@v4

    - name: Running the docker container
      uses: rhaschke/docker-run-action@v5
      with:
        image: gitlab-registry.cern.ch/cms-cloud/cmssw-docker/cmssw_10_6_30-slc7_amd64_gcc700:latest
        shell: bash
        options: ${{ env.docker_opt }}
        run: |
          echo "Listing the files"
          ls -l

          echo "Setting up CMSSW_10_6_30"
          source /cvmfs/cms.cern.ch/cmsset_default.sh
          cd /opt/cms/CMSSW_10_6_30/src
          cmsenv

          echo "Entering test_Customisers/test/"
          scram b
          cd test_Customisers/test/
          echo "#####################"
          echo "Beginning cmsRun job"
          echo "#####################"
          cmsRun test_v1_2016ULpostVFP_MC_config.py
          echo "#####################"
          echo "Ending cmsRun job"
          echo "#####################"
