name: Workflow_Test
on: 
  push:
    branches:
      - devel

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE: [cmscloud/cc7-cms]
        CMSSW_VERSION: ["CMSSW_10_6_30"]
        SCRAM_ARCH: ["slc7_amd64_gcc700"]

    env: 
        docker_opt_rw: >-
              -u 1001:1001
              -v /cvmfs:/cvmfs:shared
              -v ${{ github.workspace }}:/test_workspace
              -w /test_workspace
              -e CMSSW_VERSION=${{ matrix.CMSSW_VERSION }}
              -e SCRAM_ARCH=${{ matrix.SCRAM_ARCH }}
      
    steps:
      - name: Setting up the Repository
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
            remove-android: 'true'
            remove-haskell: 'true'
            remove-dotnet: 'true'

      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup CVMFS
        uses: cvmfs-contrib/github-action-cvmfs@v4
        with:
          cvmfs_repositories: 'cms.cern.ch'


      - name: Setup ${{ matrix.CMSSW_VERSION }} and Compilation
        uses: rhaschke/docker-run-action@v5
        with:
          image: ${{ matrix.IMAGE }}
          shell: bash
          options: ${{ env.docker_opt_rw }}
          run: |
              source /cvmfs/cms.cern.ch/cmsset_default.sh
              mkdir build_area && cd build_area
              scram project ${CMSSW_VERSION}
              cd ${CMSSW_VERSION}/src
              echo "CMSSW_10_6_30 is now available"
              cp -r /test_workspace/* ./
              cmsenv
              scram b -j 8
              ls -lah
              cd test_Customisers/
              ls -lah
