name: Workflow_Test
on: 
  push:
    branches:
      - devel

jobs:
  test_workflow:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        IMAGE: [cmscloud/cc7-cms]
        CMSSW_VERSION: ["CMSSW_10_6_30"]
        SCRAM_ARCH: ["slc7_amd64_gcc700"]

    env: 
        # docker_opt_rw: -v /cvmfs:/cvmfs:shared -v ${{ github.workspace }}:/test_workspace --mount type=bind,source=/home/cmsusr, target=/home/cmsusr -w /home/cmsusr -e CMSSW_VERSION=${{ matrix.CMSSW_VERSION }} -e SCRAM_ARCH=${{ matrix.SCRAM_ARCH }}
 
        docker_opt_rw: -v /cvmfs:/cvmfs:shared -v ${{ github.workspace }}:/test_workspace -w /test_workspace -e CMSSW_VERSION=${{ matrix.CMSSW_VERSION }} -e SCRAM_ARCH=${{ matrix.SCRAM_ARCH }}
      
    steps:
      - name: Setting up the Repository
        uses: AdityaGarg8/remove-unwanted-software@v1
        with:
            remove-android: 'true'
            remove-haskell: 'true'
            remove-dotnet: 'true'
        
      - name: Setup CVMFS 
        uses: actions/checkout@v4
      - uses: cvmfs-contrib/github-action-cvmfs@v4
        with:
          cvmfs_repositories: 'cms.cern.ch'  
      - name: Setup ${{ matrix.CMSSW_VERSION }} and Compilation
        uses: rhaschke/docker-run-action@v5
        with: 
          image: ${{ matrix.IMAGE }}
          shell: bash
          options: ${{ env.docker_opt_rw }}
          run: |
              cd /test_workspace
              source /cvmfs/cms.cern.ch/cmsset_default.sh
              scram project ${CMSSW_VERSION}
              cd ${CMSSW_VERSION}/src
              eval `scramv1 runtime -sh`
              cmsenv
              scram b -j 8
              cd test_Customisers/test/
              cmsRun test_v1_2016ULpostVFP_MC_config.py
